spring.application.name=SchoolManager
server.port=${PORT:8080}

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/school_manager}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=true